### ISSUE TITLE
dist directory was removed from gh-action branch

### ISSUE THREAD

**Issue by say8425** [technote-space/release-github-actions#397]
## Describe the bug: バグの概要

```
File not found: '/home/runner/work/_actions/say8425/aws-secrets-manager-actions/v1.3.2/dist/index.js'
```

* After run technote-space/release-github-actions@v6 action, `dist` directory and `node_modules` directory was removed from gh-action. 
  * https://github.com/say8425/aws-secrets-manager-actions/runs/1584360253?check_suite_focus=true#step:9:419 
* So my Action is [not working](https://github.com/say8425/aws-secrets-manager-actions/issues/48).

## To Reproduce: 再現手順

* run release action 
* https://github.com/say8425/aws-secrets-manager-actions/blob/master/.github/workflows/release.yml

## Expected behavior: 期待する動作

* I expect dist directory was remained from my gh-action branch as release-github-actions did that.

**Comment by technote-space** [comment]
This is because the `JS-DevTools/npm-publish` action is polluting env.

https://github.com/JS-DevTools/npm-publish/issues/15

If you do something similar to this fix, I think the problem will go away.
https://github.com/alexanderbird/where-away/commit/0cb2d3357558fe18fe9eece25b36510800481c06

**Comment by technote-space** [comment]
or I think you can use `job` to separate the environment as follows: 

```yaml
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get Yarn Cache Directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Packages
        run: yarn install
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          COMMIT_DISABLED: 1
      - name: Release to NPM Registry
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Yarn Cache Directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Release to GitHub Actions Market
        uses: technote-space/release-github-actions@v6
        with:
          PACKAGE_MANAGER: yarn
          BUILD_COMMAND: yarn package
```
