### ISSUE TITLE
`npm ci` および `npm install` が "install" コマンドとして扱われない

### ISSUE THREAD

**Issue by nogic1008** [technote-space/release-github-actions#455]
## Describe the bug: バグの概要
[npm ci コマンド](https://docs.npmjs.com/cli/v7/commands/npm-ci)は`npm install`コマンドと同じような動きをしますが、`package-lock.json`に基づいてより厳密にパッケージのインストールを行います。
そのため、[GitHub ActionsのNode.jsテンプレート](https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml)にもあるように、CI/CD環境で`npm install`の代わりとして使われています。

しかしながら、このactionでは、`BUILD_COMMAND`に`npm ci`を含めても"install"コマンドとして扱われません。
そのため、不要であるはずの`npm install`(および`npm install --production`)コマンドがビルド時に追加されてしまいます。

[`--ignore-scripts`](https://docs.npmjs.com/cli/v7/commands/npm-ci#ignore-scripts)を明示的に指定する必要がある場合[^1]に、この挙動はビルドプロセスに影響を与えます。
[^1]:[`husky`](https://typicode.github.io/husky/#/)を利用している場合など

## To Reproduce: 再現手順

1. 以下のように`npm ci`または`npm install`を含む`BUILD_COMMAND`を指定する

```yml
steps:
  - uses: technote-space/release-github-actions@v8.0.3
    with:
      BUILD_COMMAND: npm ci --ignore-scripts && npm run build
```

## Expected behavior: 期待する動作
- `npm ci`を`BUILD_COMMAND`コマンドに含む場合も、デフォルトの`npm install`を実行しない

## Screenshots: スクリーンショット
- [エラー発生時のログ](https://github.com/ddradar/lgtm-action/actions/runs/4842559268/jobs/8629587644)
  - 余計な`npm install --production`コマンドが実行されてしまったことで、`husky`コマンドがないエラーが発生している

## Operating environment: バグが発生した環境
 - technote-space/release-github-actions@v8.0.3
 - ubuntu-latest hos runner
