### ISSUE TITLE
push 時に build

### ISSUE THREAD

**Issue by technote-space** [technote-space/release-github-actions#57]
https://help.github.com/en/articles/events-that-trigger-workflows#pull-request-events-for-forked-repositories
> If you intend to use the pull_request event to trigger CI tests, we recommend that you set up your workflow configuration to listen to the push event.

```
on:
  push:
    branches:
      - "*"
    tags:
      - "!*"
```
